language: java
dist: trusty
sudo: false
before_script:
  - _JAVA_OPTIONS="-Xmx8192m -Xms512m"
script:
  # Download Rumble
  - pushd ..
  - git clone https://github.com/RumbleDB/rumble.git
  - cd rumble
  - mvn install -DskipTests -Dgpg.skip
  - popd
  
  # Download Spark
  - mkdir -p /opt
  - wget -q -O /opt/spark.tgz http://mirror.easyname.ch/apache/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz
  - tar xzf /opt/spark.tgz -C /opt/
  - rm /opt/spark.tgz
  - export SPARK_HOME=/opt/spark-2.4.4-bin-hadoop2.7
  - export PATH=$PATH:/opt/spark-2.4.4-bin-hadoop2.7/bin

  # Download and prepare dataset
  - pushd ..
  - wget -q -O confusion-2014-03-02.tbz2 http://data.greatlanguagegame.com.s3.amazonaws.com/confusion-2014-03-02.tbz2
  - tar -xvjf confusion-2014-03-02.tbz2
  - rm  confusion-2014-03-02.tbz2
  - cd confusion-2014-03-02
  - head -n 500000 confusion-2014-03-02.json > confusion500k.json
  - head -n 5000000 confusion-2014-03-02.json > confusion5m.json
  - popd

  - ./compare-branches.sh 1.1 master 1 large
cache:
  directories:
    - $HOME/.m2


